### PR TITLE
publish-0.8.0-beta

### PR DESCRIPTION
**Pull request by IngridGdesigns**
last minute update to files for new release - updated typescript-eslint parser due to error while running npm lint

### CODE REVIEW

**Review by keeganwitt — APPROVED** [review]
I don't think we have any Husky [migration steps](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7) to do, so if this resolved the ESLint error, it looks good to me.

**Review by kevindigo — CHANGES_REQUESTED** [review]
This looks fine, except for my question (asked in another channel) about whether this should be 0.8.0 or 0.7.1. If the answer turns out to be 0.8.0, this is approved by me.

**Comment by keeganwitt** [comment]
> This looks fine, except for my question (asked in another channel) about whether this should be 0.8.0 or 0.7.1. If the answer turns out to be 0.8.0, this is approved by me.

The GitHub flavored Markdown is a new feature, so a new minor version is appropriate.

**Review by kevindigo — APPROVED** [review]

**Comment by IngridGdesigns** [comment]
Merged https://github.com/indeedeng/Mariner/pull/119 (added HTML section in README)

**Pull request merged**
