### PR TITLE
Add shields.io badges

### PR DESCRIPTION
**Pull request by jk10274**
This is fixing issue #104 including:
- license
- project language
- issues
- maintained

### CODE REVIEW

**Review by IngridGdesigns — APPROVED** [review]
Looks great, thanks @jk10274!

**Comment by IngridGdesigns** [comment]
@danisyellis do you have any other badge suggestions?

**Comment by Ray0Emma** [comment]
Hi @jk10274! I think  you have missed the issues badge, you can add this : 

`[GitHub issues open](https://github.com/indeedeng/Mariner/issues)`

[GitHub issues open](https://github.com/indeedeng/Mariner/issues)

**Comment by IngridGdesigns** [comment]
Nice catch @Ray0Emma

**Comment by IngridGdesigns** [comment]
Hello @jk10274, when you get a chance, please add issues badge

**Comment by jk10274** [comment]
Thanks, the issues badge is now added.

**Comment by IngridGdesigns** [comment]
@jk10274 Thanks!

**Pull request merged**
