### PR TITLE
Update Dependencies to latest

### PR DESCRIPTION
**Pull request by GuyKh**
Updated dependencies:
```
 @octokit/graphql                    ^4.5.5  →    ^4.5.6
 @types/node-fetch                   ^2.5.5  →    ^2.5.7
 moment                             ^2.24.0  →   ^2.29.0
 typescript                          ^3.8.3  →    ^4.0.3
 @types/node                       ^13.13.2  →  ^14.11.2
 @typescript-eslint/eslint-plugin   ^2.28.0  →    ^4.3.0
 @typescript-eslint/parser          ^2.28.0  →    ^4.3.0
 eslint                              ^6.8.0  →   ^7.10.0
 eslint-config-prettier             ^6.10.1  →   ^6.12.0
 eslint-plugin-prettier              ^3.1.3  →    ^3.1.4
 prettier                            ^2.0.4  →    ^2.1.2
```

### CODE REVIEW

**Comment by kevindigo** [comment]
Thanks for this contribution. We had to make another change to package-lock today, and we'll be making one more over the next couple days. So you'll need to merge those changes into this. We're super busy the rest of this week, but if this PR is updated early next week, and tested, we can merge it then. Please include a note indicating that you were able to successfully run the example (runFasterCode.ts) with these updates applied.

**Comment by GuyKh** [comment]
@kevindigo 
👍🏻 
Ran the example now - all works - `output.json` created

**Comment by IngridGdesigns** [comment]
Verified that both files produce an output.json file with the dependency updates

**Review by IngridGdesigns — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
